name: mixagram
description: "Sweet Mixagram - MindStorm Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  google_fonts:
  http: ^1.1.0
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bg/
    - assets/icons/
    - assets/images/
    - assets/music/
